### ISSUE TITLE
Rename: Gaslight to Launch Scout

### ISSUE THREAD

**Issue by pkananen** [FrancesCoronel/apprenticeships#559]
## Which apprenticeship are you trying to edit?

Gaslight

## What edits do you want to make?

We changed our company name to Launch Scout. Our web address is launchscout.com. We updated the link, so it redirects correctly, but you can change it to: https://launchscout.com/careers/developer-apprenticeship.

The description text can be changed to: 

"Launch Scout's apprenticeship program is designed to match client companies looking to build a development team with enthusiastic, high-aptitude beginning developers."

Logo is attached.

Location is Cincinnati, Ohio and Remote
![rgb_launch-scout-logo_full-color](https://user-images.githubusercontent.com/444429/211674613-7f28d88b-af8d-4716-a276-e5eac884aa8e.png)

---

**Comment by FrancesCoronel** [comment]
Thanks for the update - I will edit this once I get a chance!
